# Generated by Django 6.0.5 on 2026-05-08 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('color', models.CharField(max_length=100, verbose_name='color')),
                ('current_weight', models.FloatField(help_text='Current weight in kilograms', validators=[django.core.validators.MinValueValidator(0.0, 'Weight must be greater than 0')], verbose_name='weight')),
                ('birth_weight', models.FloatField(blank=True, help_text='Birth weight in kilograms', null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Birth weight must be greater than 0')], verbose_name='birth_weight')),
                ('is_sterilized', models.BooleanField(default=False, verbose_name='is_sterilized')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('FOR_DEMONSTRATION', 'Only for demonstration'), ('AWAITING_OWNER', 'Awaiting of new owner'), ('GIVEN_AWAY', 'Given away'), ('CLOSED', 'Closed')], default='AWAITING_OWNER', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='cats.breed')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_mother', to='cats.cat', verbose_name='father')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_father', to='cats.cat', verbose_name='mother')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'indexes': [models.Index(fields=['breed', 'gender'], name='cats_cat_breed_i_5b5ea7_idx'), models.Index(fields=['status'], name='cats_cat_status_b48d4c_idx')],
            },
        ),
    ]
