# Generated by Django 6.0.5 on 2026-05-08 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['birthday'], name='cats_cat_birthda_3d9bcb_idx'),
        ),
    ]
