# Generated by Django 6.0.5 on 2026-05-08 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_cats_cat_birthda_3d9bcb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0, 'Price must be greater than 0')], verbose_name='price'),
        ),
    ]
