# Generated by Django 6.0.5 on 2026-05-09 00:50

import cats.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cat_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=cats.models.get_location_for_upload)),
                ('is_main', models.BooleanField(default=False, verbose_name='is_main')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cats.cat')),
            ],
            options={
                'indexes': [models.Index(fields=['cat'], name='cats_catima_cat_id_b46a38_idx'), models.Index(fields=['cat', 'is_main'], name='cats_catima_cat_id_7b4e92_idx')],
            },
        ),
    ]
