# Generated by Django 6.0.5 on 2026-05-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_catimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='hair_type',
            field=models.CharField(choices=[('SHORT', 'Short'), ('MEDIUM', 'Medium'), ('LONG', 'Long'), ('HAIRLESS', 'Hairless'), ('CURLY', 'Curly'), ('UNKNOWN', 'UNKNOWN')], default='U', max_length=10, verbose_name='hair_type'),
            preserve_default=False,
        ),
    ]
