# Generated by Django 6.0.5 on 2026-05-12 00:15
from django.core.management import call_command
from django.db import migrations

def load_fixtures(apps, schema_editor):
    """Загружает фикстуры при миграции"""
    call_command('loaddata', 'cats/fixtures/initial_breeds.json')


def reverse_load_fixtures(apps, schema_editor):
    """Откат (опционально)"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_breed_hair_type'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_load_fixtures),
    ]
