# Generated by Django 6.0.5 on 2026-05-12 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_load_initial_breeds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteCat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='cats.cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_cats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cat', 'user')},
            },
        ),
    ]
