services:
  db:
    image: postgres:18
    container_name: db
    restart: always
    networks:
      - internal-network
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  minio:
    image: minio/minio
    restart: always
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    env_file:
      - .env
    networks:
      - internal-network
    volumes:
      - minio-volume:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  create-buckets:
    image: minio/mc
    restart: no
    container_name: create-buckets
    depends_on:
      - minio
    networks:
      - internal-network
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin};
      /usr/bin/mc mb myminio/${MINIO_DEFAULT_BUCKET_NAME:-bucket};
      /usr/bin/mc anonymous set public myminio/${MINIO_DEFAULT_BUCKET_NAME:-bucket};
      exit 0;
      "

  backend:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
      target: development
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - internal-network
    depends_on:
      - db
      - minio
    develop:
      watch:
        - path: ./backend_service
          action: sync
          target: ./app
          ignore:
            - .venv
            - ./backend_service/.venv
        - path: ./backend_service/requirements.txt
          action: rebuild
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG?Variable not set}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER?Variable not set}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD?Variable not set}
      - AWS_STORAGE_BUCKET_NAME=${MINIO_DEFAULT_BUCKET_NAME?Variable not set}
      - AWS_S3_ENDPOINT_URL=${MINIO_ENDPOINT_URL?Variable not set}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}


networks:
  internal-network:
    driver: bridge

volumes:
  minio-volume:
  app-db-data:
